### ISSUE TITLE
Error with LOG_BASED replication when there is an empty document/ no new data in change stream

### ISSUE THREAD

**Issue by Joseph-A-Pearson** [MeltanoLabs/tap-mongodb#26]
When performing log-based replication from mongodb, if there is no new records in the change stream an empty document is returned. The tap then tries to parse the object_id from the empty document and errors out, because python can't iterate through an object that doesn't exist.

The error is due to this line `object_id: Optional[ObjectId] = document["_id"] if "_id" in document else None 
`
meltano version 3.1.0

```
2023-10-30T12:36:44.366066Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366209Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1179, in sync cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366351Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366507Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1073, in _sync_records cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366650Z [info     ]     for record_result in self.get_records(current_context): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366788Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/tap_mongodb/streams.py", line 344, in get_records cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.366927Z [info     ]     object_id: Optional[ObjectId] = document["_id"] if "_id" in document else None cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367065Z [info     ] TypeError: argument of type 'NoneType' is not iterable cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367202Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367351Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/bin/tap-mongodb", line 8, in <module> cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367489Z [info     ]     sys.exit(TapMongoDB.cli()) cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367628Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__ cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367833Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.367976Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368117Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368255Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368393Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368530Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368666Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368802Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 500, in invoke cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.368938Z [info     ]     tap.sync_all()             cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369075Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 459, in sync_all cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369217Z [info     ]     stream.sync()              cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369354Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1186, in sync cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369491Z [info     ]     raise ex                   cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369644Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1179, in sync cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369786Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.369922Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1073, in _sync_records cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.370059Z [info     ]     for record_result in self.get_records(current_context): cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.370196Z [info     ]   File "/project/.meltano/extractors/tap-mongodb-live/venv/lib/python3.9/site-packages/tap_mongodb/streams.py", line 344, in get_records cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.370384Z [info     ]     object_id: Optional[ObjectId] = document["_id"] if "_id" in document else None cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
2023-10-30T12:36:44.370526Z [info     ] TypeError: argument of type 'NoneType' is not iterable cmd_type=elb consumer=False name=tap-mongodb-us producer=True stdio=stderr string_id=tap-mongodb-us
```

**Comment by Joseph-A-Pearson** [comment]
closed as this was not the cause of the issue
